/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCSlugRouteImport } from './routes/_app/c.$slug'
import { Route as AppCSlugItemRouteImport } from './routes/_app/c_.$slug.$item'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCSlugRoute = AppCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCSlugItemRoute = AppCSlugItemRouteImport.update({
  id: '/c_/$slug/$item',
  path: '/c/$slug/$item',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/c/$slug': typeof AppCSlugRoute
  '/c/$slug/$item': typeof AppCSlugItemRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/c/$slug': typeof AppCSlugRoute
  '/c/$slug/$item': typeof AppCSlugItemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/c/$slug': typeof AppCSlugRoute
  '/_app/c_/$slug/$item': typeof AppCSlugItemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$slug' | '/c/$slug/$item'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$slug' | '/c/$slug/$item'
  id: '__root__' | '/_app' | '/_app/' | '/_app/c/$slug' | '/_app/c_/$slug/$item'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c/$slug': {
      id: '/_app/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof AppCSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c_/$slug/$item': {
      id: '/_app/c_/$slug/$item'
      path: '/c/$slug/$item'
      fullPath: '/c/$slug/$item'
      preLoaderRoute: typeof AppCSlugItemRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCSlugRoute: typeof AppCSlugRoute
  AppCSlugItemRoute: typeof AppCSlugItemRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCSlugRoute: AppCSlugRoute,
  AppCSlugItemRoute: AppCSlugItemRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
